#!/usr/bin/env bash
# Install nginx

apt update
apt install -y nginx

# Set up nginx configuration
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 "Hello World!\n";
    }
}
EOF

# Restart nginx
kill -HUP $(pgrep nginx)

echo "Nginx installed and configured successfully."
