#!/usr/bin/env bash
# sets up a new 404 error pag  with index and 301 page
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
