#!/usr/bin/env bash
# Install the load balancer

sudo apt-get -y update
sudo apt install -y haproxy=1.8.\*
file="/etc/haproxy/haproxy.cfg"

# Append frontend configuration to haproxy.cfg
sudo tee -a $file <<EOF
frontend haproxynode
    bind *:80
    mode http
    default_backend nodes
EOF

# Append backend configuration to haproxy.cfg
sudo tee -a $file <<EOF
backend nodes
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    server 416344-web-01 54.90.31.96:80 check
    server 416344-web-02 100.26.156.63:80 check
EOF

# Restart HAProxy
sudo service haproxy restart
