#!/usr/bin/env bash
# Using 'while' loop and IFS to parse /etc/passwd

while IFS=: read -r username _ userid groupid info homedir shell; do
    user_info=$(echo "$info" | cut -d',' -f1)
    passcode=$(echo "$info" | cut -d',' -f2)
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "$userid's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd
