#!/usr/bin/env bash
# Run Nginx as Nginx
sudo sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*[^;]*;/listen *8080;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
